version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: yarpee
      POSTGRES_PASSWORD: yarpee
      POSTGRES_DB: yarpee
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yarpee"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      YARPEE__DB__CONNECTIONSTRING: "Host=db;Port=5432;Database=yarpee;Username=yarpee;Password=yarpee"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgdata:
